//! Session rendering for HTML and Markdown export

use crate::error::Result;
use crate::event::{Event, Role, SessionManifest};
use chrono::{DateTime, Utc};

/// Minimal highlight.js subset for syntax highlighting
/// Embedded directly to avoid external dependencies
const HLJS_SUBSET: &str = include_str!("../assets/hljs-subset.min.js");

/// Render a session as self-contained HTML
pub fn render_html(events: &[Event], meta: &SessionManifest) -> Result<String> {
    let duration = format_duration(meta.started, meta.ended);
    let models = format_models(meta.model.as_deref());

    let mut html = String::from("<!DOCTYPE html>\n");
    html.push_str("<html lang=\"en\">\n");
    html.push_str("<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("<title>");
    html.push_str(&escape_html(&meta.session_id));
    html.push_str(" - AgentScribe Session</title>\n");
    html.push_str("<style>\n");
    html.push_str(CSS);
    html.push_str("\n</style>\n");
    html.push_str("</head>\n");
    html.push_str("<body>\n");

    // Header
    html.push_str("<header>\n");
    html.push_str("<div class=\"header-row\"><span class=\"header-label\">Project:</span><span class=\"header-value\">");
    html.push_str(&escape_html(meta.project.as_deref().unwrap_or("unknown")));
    html.push_str("</span></div>\n");
    html.push_str("<div class=\"header-row\"><span class=\"header-label\">Agent:</span><span class=\"header-value\">");
    html.push_str(&escape_html(&meta.source_agent));
    html.push_str("</span></div>\n");
    if let Some(outcome) = &meta.outcome {
        html.push_str("<div class=\"header-row\"><span class=\"header-label\">Outcome:</span><span class=\"header-value\">");
        html.push_str(&escape_html(outcome));
        html.push_str("</span></div>\n");
    }
    html.push_str("<div class=\"header-row\"><span class=\"header-label\">Duration:</span><span class=\"header-value\">");
    html.push_str(&duration);
    html.push_str("</span></div>\n");
    if !models.is_empty() {
        html.push_str("<div class=\"header-row\"><span class=\"header-label\">Models:</span><span class=\"header-value\">");
        html.push_str(&models);
        html.push_str("</span></div>\n");
    }
    if !meta.files_touched.is_empty() {
        html.push_str("<div class=\"header-row\"><span class=\"header-label\">Files touched:</span><span class=\"header-value\">");
        html.push_str(&escape_html(&meta.files_touched.join(", ")));
        html.push_str("</span></div>\n");
    }
    html.push_str("</header>\n");

    // Conversation
    html.push_str("<div class=\"conversation\">\n");

    for event in events {
        let role_class = match event.role {
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::System => "system",
            Role::ToolCall => "tool-call",
            Role::ToolResult => "tool-result",
        };

        html.push_str("<div class=\"turn\">\n");
        html.push_str("<div class=\"turn-header\">\n");
        html.push_str("<span class=\"role-badge role-");
        html.push_str(role_class);
        html.push_str("\">");
        html.push_str(role_badge_label(&event.role));
        html.push_str("</span>\n");
        html.push_str("<span class=\"timestamp\">");
        html.push_str(&format_timestamp(&event.ts));
        html.push_str("</span>\n");
        if let Some(ref tool) = event.tool {
            html.push_str("<span class=\"tool-name\">");
            html.push_str(&escape_html(tool));
            html.push_str("</span>\n");
        }
        html.push_str("</div>\n"); // turn-header

        html.push_str("<div class=\"turn-content\">\n");
        html.push_str(&render_content_html(&event.content));
        html.push_str("</div>\n"); // turn-content
        html.push_str("</div>\n"); // turn
    }

    html.push_str("</div>\n"); // conversation

    // Footer
    html.push_str("<footer>\n");
    html.push_str("<div class=\"footer-row\">Session: ");
    html.push_str(&escape_html(&meta.session_id));
    html.push_str("</div>\n");
    html.push_str("<div class=\"footer-row\">Generated by AgentScribe at ");
    html.push_str(&Utc::now().to_rfc3339());
    html.push_str("</div>\n");
    html.push_str("</footer>\n");

    // Syntax highlighting script
    html.push_str("<script>\n");
    html.push_str(HLJS_SUBSET);
    html.push_str("\ndocument.addEventListener('DOMContentLoaded', function() {\n");
    html.push_str("  hljs.highlightAll();\n");
    html.push_str("});\n");
    html.push_str("</script>\n");

    html.push_str("</body>\n");
    html.push_str("</html>\n");

    Ok(html)
}

/// Render a session as structured Markdown
pub fn render_markdown(events: &[Event], meta: &SessionManifest) -> Result<String> {
    let mut md = String::new();

    // YAML frontmatter
    md.push_str("---\n");
    md.push_str(&format!("session_id: {}\n", meta.session_id));
    md.push_str(&format!("source_agent: {}\n", meta.source_agent));
    if let Some(ref project) = meta.project {
        md.push_str(&format!("project: {}\n", project));
    }
    md.push_str(&format!("started: {}\n", meta.started.to_rfc3339()));
    if let Some(ref ended) = meta.ended {
        md.push_str(&format!("ended: {}\n", ended.to_rfc3339()));
    }
    md.push_str(&format!("turns: {}\n", meta.turns));
    if let Some(ref outcome) = meta.outcome {
        md.push_str(&format!("outcome: {}\n", outcome));
    }
    if !meta.files_touched.is_empty() {
        md.push_str("files_touched:\n");
        for file in &meta.files_touched {
            md.push_str(&format!("  - {}\n", file));
        }
    }
    if let Some(ref model) = meta.model {
        md.push_str(&format!("model: {}\n", model));
    }
    md.push_str("---\n\n");

    // Summary if available
    if let Some(ref summary) = meta.summary {
        md.push_str(&format!("**Summary:** {}\n\n", summary));
    }

    // Conversation
    for event in events {
        let role_label = match event.role {
            Role::User => "**User**",
            Role::Assistant => "**Assistant**",
            Role::System => "**System**",
            Role::ToolCall => "**Tool Call**",
            Role::ToolResult => "**Tool Result**",
        };

        md.push_str(&format!(
            "{} ({})\n\n",
            role_label,
            format_timestamp(&event.ts)
        ));

        if let Some(ref tool) = event.tool {
            md.push_str(&format!("*Tool: {}*\n\n", tool));
        }

        // Render content with code blocks preserved
        md.push_str(&render_content_markdown(&event.content));
        md.push_str("\n\n---\n\n");
    }

    Ok(md)
}

/// Render content with code block detection for HTML
fn render_content_html(content: &str) -> String {
    let mut result = String::new();
    let mut pos = 0;

    // Detect code blocks: ```lang ... ```
    while let Some(fence_start) = content[pos..].find("```") {
        // Add text before fence
        let before_fence = &content[pos..pos + fence_start];
        result.push_str(&escape_html(before_fence));

        pos += fence_start + 3;

        // Extract language (rest of line)
        let lang_end = content[pos..].find('\n').unwrap_or(content[pos..].len());
        let lang = &content[pos..pos + lang_end];
        let lang = lang.trim();

        pos += lang_end + 1; // Skip newline

        // Find closing fence
        if let Some(fence_end) = content[pos..].find("```") {
            let code = &content[pos..pos + fence_end];

            result.push_str("<pre><code class=\"language-");
            result.push_str(&escape_html(lang));
            result.push_str("\">");
            result.push_str(&escape_html(code));
            result.push_str("</code></pre>");

            pos += fence_end + 3;

            // Skip trailing newline
            if pos < content.len() && content.as_bytes()[pos] == b'\n' {
                pos += 1;
            }
        } else {
            // No closing fence, treat rest as text
            result.push_str("<pre>");
            result.push_str(&escape_html(&content[pos..]));
            result.push_str("</pre>");
            break;
        }
    }

    // Add remaining text
    if pos < content.len() {
        result.push_str(&escape_html(&content[pos..]));
    }

    result
}

/// Render content with code block detection for Markdown
fn render_content_markdown(content: &str) -> String {
    // For Markdown, we mostly preserve the original formatting
    // Just ensure newlines are handled correctly
    content.to_string()
}

/// Format duration between start and end
fn format_duration(start: DateTime<Utc>, end: Option<DateTime<Utc>>) -> String {
    let end = end.unwrap_or_else(Utc::now);
    let duration = end.signed_duration_since(start);

    let mut parts: Vec<String> = Vec::new();

    if duration.num_days() > 0 {
        parts.push(format!("{}d", duration.num_days()));
    }
    if duration.num_hours() % 24 > 0 {
        parts.push(format!("{}h", duration.num_hours() % 24));
    }
    if duration.num_minutes() % 60 > 0 {
        parts.push(format!("{}m", duration.num_minutes() % 60));
    }

    if parts.is_empty() {
        "<1m".to_string()
    } else {
        parts.join(" ")
    }
}

/// Format model(s) used
fn format_models(model: Option<&str>) -> String {
    model.unwrap_or("unknown").to_string()
}

/// Format timestamp for display
fn format_timestamp(ts: &DateTime<Utc>) -> String {
    ts.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}

/// Get role badge label
fn role_badge_label(role: &Role) -> &'static str {
    match role {
        Role::User => "User",
        Role::Assistant => "Assistant",
        Role::System => "System",
        Role::ToolCall => "Tool",
        Role::ToolResult => "Result",
    }
}

/// Escape HTML special characters
fn escape_html(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => result.push_str("&amp;"),
            '<' => result.push_str("&lt;"),
            '>' => result.push_str("&gt;"),
            '"' => result.push_str("&quot;"),
            '\'' => result.push_str("&#x27;"),
            c => result.push(c),
        }
    }
    result
}

/// Inline CSS for HTML output (~3KB budget)
const CSS: &str = r#"
:root {
  --bg: #ffffff;
  --fg: #1a1a1a;
  --border: #e0e0e0;
  --header-bg: #f5f5f5;
  --code-bg: #f8f8f8;
  --user-bg: #e3f2fd;
  --assistant-bg: #f3e5f5;
  --system-bg: #fff3e0;
  --tool-bg: #e8f5e9;
  --tool-result-bg: #fce4ec;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a1a;
    --fg: #e0e0e0;
    --border: #333333;
    --header-bg: #2d2d2d;
    --code-bg: #252525;
    --user-bg: #1e3a5f;
    --assistant-bg: #3e2e5f;
    --system-bg: #5f4e1e;
    --tool-bg: #1e5f3e;
    --tool-result-bg: #5f1e3e;
  }
}

* { box-sizing: border-box; }

body {
  margin: 0;
  padding: 0;
  font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Fira Mono', 'Droid Sans Mono', 'Source Code Pro', monospace;
  font-size: 14px;
  line-height: 1.6;
  background: var(--bg);
  color: var(--fg);
}

header {
  padding: 16px;
  border-bottom: 1px solid var(--border);
  background: var(--header-bg);
}

.header-row {
  display: flex;
  gap: 8px;
  margin: 4px 0;
}

.header-label {
  font-weight: 600;
  min-width: 100px;
}

.conversation {
  padding: 16px;
  max-width: 900px;
  margin: 0 auto;
}

.turn {
  margin: 16px 0;
  border: 1px solid var(--border);
  border-radius: 4px;
  overflow: hidden;
}

.turn-header {
  padding: 8px 12px;
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  gap: 12px;
  background: var(--header-bg);
}

.role-badge {
  padding: 2px 8px;
  border-radius: 3px;
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
}

.role-user { background: var(--user-bg); }
.role-assistant { background: var(--assistant-bg); }
.role-system { background: var(--system-bg); }
.role-tool-call { background: var(--tool-bg); }
.role-tool-result { background: var(--tool-result-bg); }

.timestamp {
  color: var(--fg);
  opacity: 0.7;
  font-size: 12px;
}

.tool-name {
  font-family: inherit;
  background: var(--code-bg);
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 12px;
}

.turn-content {
  padding: 12px;
  white-space: pre-wrap;
  word-wrap: break-word;
}

pre {
  background: var(--code-bg);
  padding: 12px;
  border-radius: 4px;
  overflow-x: auto;
  margin: 8px 0;
}

code {
  font-family: inherit;
  font-size: 13px;
}

:not(pre) > code {
  background: var(--code-bg);
  padding: 2px 6px;
  border-radius: 3px;
}

footer {
  padding: 16px;
  border-top: 1px solid var(--border);
  background: var(--header-bg);
  margin-top: 32px;
}

.footer-row {
  font-size: 12px;
  opacity: 0.7;
  margin: 4px 0;
}

/* Syntax highlighting colors (light/dark via CSS variables) */
.hljs { display: block; overflow-x: auto; padding: 0; }
.hljs-comment, .hljs-quote { color: #6a9955; font-style: italic; }
.hljs-keyword, .hljs-selector-tag, .hljs-subst { color: #569cd6; }
.hljs-number, .hljs-literal, .hljs-variable, .hljs-template-variable { color: #b5cea8; }
.hljs-string, .hljs-doctag { color: #ce9178; }
.hljs-title, .hljs-section, .hljs-selector-id { color: #dcdcaa; }
.hljs-type, .hljs-class .hljs-title { color: #4ec9b0; }
.hljs-tag, .hljs-name, .hljs-attribute { color: #569cd6; }
.hljs-regexp, .hljs-link { color: #d16969; }
.hljs-symbol, .hljs-bullet { color: #4ec9b0; }
.hljs-built_in, .hljs-builtin-name { color: #4ec9b0; }
.hljs-meta { color: #6a9955; }
.hljs-deletion { background: #fdd; }
.hljs-addition { background: #dfd; }
.hljs-emphasis { font-style: italic; }
.hljs-strong { font-weight: bold; }

@media (prefers-color-scheme: dark) {
  .hljs-comment, .hljs-quote { color: #6a9955; }
  .hljs-keyword, .hljs-selector-tag, .hljs-subst { color: #c586c0; }
  .hljs-number, .hljs-literal { color: #b5cea8; }
  .hljs-string, .hljs-doctag { color: #ce9178; }
  .hljs-title, .hljs-section { color: #dcdcaa; }
  .hljs-type, .hljs-class .hljs-title { color: #4ec9b0; }
  .hljs-tag, .hljs-name { color: #569cd6; }
  .hljs-attr { color: #9cdcfe; }
  .hljs-symbol { color: #4ec9b0; }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_html_basic() {
        let events = vec![Event::new(
            Utc::now(),
            "test/123".to_string(),
            "test".to_string(),
            Role::User,
            "Hello, world!".to_string(),
        )];
        let meta = SessionManifest::new("test/123".to_string(), "test".to_string());

        let html = render_html(&events, &meta).unwrap();
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("Hello, world!"));
        assert!(html.contains("role-user"));
    }

    #[test]
    fn test_render_markdown_basic() {
        let events = vec![Event::new(
            Utc::now(),
            "test/123".to_string(),
            "test".to_string(),
            Role::User,
            "Hello, world!".to_string(),
        )];
        let meta = SessionManifest::new("test/123".to_string(), "test".to_string());

        let md = render_markdown(&events, &meta).unwrap();
        assert!(md.starts_with("---\n"));
        assert!(md.contains("**User**"));
        assert!(md.contains("Hello, world!"));
    }

    #[test]
    fn test_render_html_with_code_block() {
        let events = vec![Event::new(
            Utc::now(),
            "test/123".to_string(),
            "test".to_string(),
            Role::Assistant,
            "Here is some code:\n```rust\nfn main() {}\n```".to_string(),
        )];
        let meta = SessionManifest::new("test/123".to_string(), "test".to_string());

        let html = render_html(&events, &meta).unwrap();
        assert!(html.contains("<pre><code class=\"language-rust\">"));
        assert!(html.contains("fn main() {}"));
    }

    #[test]
    fn test_escape_html() {
        assert_eq!(escape_html("<script>"), "&lt;script&gt;");
        assert_eq!(escape_html("a & b"), "a &amp; b");
        assert_eq!(escape_html("\"quoted\""), "&quot;quoted&quot;");
    }

    #[test]
    fn test_format_duration() {
        let start = Utc::now();
        let end = start + chrono::Duration::hours(2) + chrono::Duration::minutes(30);
        assert_eq!(format_duration(start, Some(end)), "2h 30m");
    }
}
